### PR TITLE
add SSE2 simd for dwt_shift_rem and diff_count

### PR DESCRIPTION
**Pull request by jsorg71**
make dwt_shift_rem easier to read
move common rlgr defines to common file
move common dwt defines to common file

### CODE REVIEW

**Comment by jsorg71** [comment]
In my tests dwt_shift got 5+ times faster and diff_count got 6+ times faster.

**Comment by matt335672** [comment]
I'm not really qualified to comment on this, but those sort of results sound pretty good!

**Comment by metalefty** [comment]
Let's merge this and test in v0.10 beta releases.

**Comment by matt335672** [comment]
@jsorg71 - are you planning on making more changes to this library?

If not, I'll update the submodule reference, backport to v0.10 and update the NEWS files.

**Comment by jsorg71** [comment]
@matt335672 no, no more changes with the SSE2.  I do plan a NEON version in the future.

**Pull request merged**
