### PR TITLE
Include config_ac.h in all sources, make use of it

### PR DESCRIPTION
**Pull request by proski**

### CODE REVIEW

**Comment by jsorg71** [comment]
Should be wrapped with
#if defined(HAVE_CONFIG_H) ?

**Comment by proski** [comment]
I can do it, but I'd rather not.

HAVE_CONFIG_H is for files that may be built both with and without Autoconf generated header. We don't provide an option to skip `configure`

HAVE_CONFIG_H implies that the configuration file is called `config.h`, not `config_ac.h`

**Comment by jsorg71** [comment]
We have to discus if that is a new policy.
We build with autotools but not everyone uses it.

**Comment by proski** [comment]
Users of xrdp don't need Autotools to compile xrdp. They need to run `configure`, and it would be very hard to compile xrdp without that step. `config_ac.h` is generated by `configure` from a template included in the distribution.

Even if somebody wands to replace `configure` with some other mechanism, it would be more convenient for them to create `config_ac.h` than to add defines to the compiler command line.

**Comment by proski** [comment]
I've updated the PR to check `HAVE_CONFIG_H`

**Comment by jsorg71** [comment]
I'm not saying that we should not remove the #if, we just should discuss the side effect.
I do consider configure = autotools, it's the autotools way.
There are people using xrdp that do not run configure.  They make their own makefiles or IDE projects.

**Comment by proski** [comment]
Actually, I tried working on xrdp in Eclipse. It's aware of `configure`. It was quite smooth, I think it's possible to do actual development like that. I don't see why `configure` should be avoided.

It I use `HAVE_STDINT_H` in the code, I rely on `configure` enabling that define in the config header. If somebody skips `configure`, they could miss that symbol and get strange results. If they define `HAVE_CONFIG_H`, I can assume they created `config_ac.h` and populated it with some reasonable values. If they didn't define `HAVE_CONFIG_H`, I simply don't know what to do. I cannot detect presence of headers from the C code. Assuming that everything is missing leads to poor code that doesn't work well (if at all) for most users or is hard to maintain and debug.

I'm not interested in supporting xrdp without `configure`. I don't care if the check for `HAVE_CONFIG_H` is present. Let's decide and do it one way or another.

**Pull request merged**
