### PR TITLE
Add GNU/kFreeBSD support

### PR DESCRIPTION
**Pull request by mirabilos**
Recognise GNU/kFreeBSD for NASM.

### CODE REVIEW

**Comment by proski** [comment]
+1

**Comment by jsorg71** [comment]
Looks like this is taken care of in #20

**Comment by mirabilos** [comment]
Yes, looks like it. Would have been nice of @proski to use --author for the one commit from here, but, oh my.

**Comment by proski** [comment]
I actually synchronized `nasm.m4` from xorgxrdp. The idea of this move was to have a file that says what's inside and that can be easily shared between projects (not so easy with `aclocal.m4` that may include other stuff). I was not aware of this PR when I committed the change. I agree, your name should have been on the patch. Sorry.

**Pull request closed without merging**
